### ISSUE TITLE
[BUG] Minor Incapability with Midi QoL

### ISSUE THREAD

**Issue by alcobeard** [Moerill/fvtt-mars-5e#10]
I'm not sure if it is a big problem, but just want to notify

After enabling Midi QoL module GM/Player can't roll item/spell.
Error log leads to entity.js

```
Uncaught (in promise) TypeError: Cannot read property 'shortenedFormula' of undefined
    at MarsItem5e.displayCard (entity.js:217)
```
line in entity.js

```
const mod = attackRoll.shortenedFormula.replace(/[12]?d20(k[hl])?\s/,
          ""
        );
``` 
Disabled all functions in Midi QoL that overwrites roll behavior and problem disappeared. Especially this one below
![image](https://user-images.githubusercontent.com/16816663/102409635-403f2a80-3fa4-11eb-9973-bb8d847ab7a9.png)
So, I think it's not a problem and there is no need to do something, just want to notify you, so you could add this moment to description and other users of your cool modules won't bother you with this error

![image](https://user-images.githubusercontent.com/16816663/102407817-91015400-3fa1-11eb-8cc3-04f0c6d0af72.png)
![image](https://user-images.githubusercontent.com/16816663/102407861-a0809d00-3fa1-11eb-902c-6cdb256a5291.png)

 - OS: Windows 10, MacOS Big Sur, Ubuntu 18.04
 - Browser: chrome
 - FVTT Version 0.7.8
 - Module version latest

**Comment by Moerill** [comment]
Thanks for testing this.

I should probably write this into the README, but this specific option is bound to cause problems and will not be compatible. (Both that option and mars kinda try to do similar things on completly different ways)

**Comment by Moerill** [comment]
Added to README

**Comment by alcobeard** [comment]
Hi. I want to add that MidiQoL totally incompatible because of critical hit automation. While using both of modules, when GM/User rolls 20 auto calculation of critical damage brakes. At the same time, if gm/user rolls <20 and gm switch damage modifier to critical before rolling damage everything is working correct. I had hope, that I could switch of critical hit calculation in MidiQoL, but there is no way to do this. 

So, at this moment MidiQoL and Mars incompatible

**Comment by Moerill** [comment]
Thanks for testing. I've taken quick look at Midi and being incompatible is wrong, since MidiQoL does so much stuff. But *everything* that has to do anything with modifying how rolling works, will not work. (And i will not try to change that, since they both 2 completly different ways to tackle a similar problem)  
i've taken a quick look at the midi QoL settings menu and took an educated guess, which will not work, here are my results:  
![image](https://user-images.githubusercontent.com/26152015/102891011-c30d2d00-445d-11eb-8deb-917e161e9327.png)  
The wave is a .. yes it works, *but* ignores all of mars for it. (it seems)


If someone is willing to properly do a real test for each setting, feel free to post it here / send me the results and i'll add them.
