### ISSUE TITLE
[BUG] Mars not showing in Module Settings

### ISSUE THREAD

**Issue by siliconsaint** [Moerill/fvtt-mars-5e#23]
Mars not showing in Module Settings for me.

Current versions & settings of everything:
Mars .2.3
Foundry .7.8
DND5e 1.2.0
MESS Installed but deactivated

Let me know what else I may provide.

**Comment by Moerill** [comment]
Since you use the term "settings", do you really mean "settings", or did you mean "Module Management"?  
![image](https://user-images.githubusercontent.com/26152015/102695660-05015d80-4229-11eb-8a80-f10dd57ff7e2.png)
in the settings (1) you won't find it, since it doesn't have any settings (currently)

**Comment by siliconsaint** [comment]
You are correct, I was anticipating a config screen. Apologies for the trouble!
