### ISSUE TITLE
Few issues 

### ISSUE THREAD

**Issue by highnrgappalachian** [Moerill/fvtt-mars-5e#51]
- Bug: Attempting to attack with an item that has a designated item track from Maestro will result in an error in console and the sound will not play.

Feature requests:
- Make it so that the GM can still attack with an item that's configured to use a resource when the resource is empty or not present. As it is currently, that's impossible. You could do that with MESS, even though a warning popped up.
- The right-click behavior to roll with adv/disadvantage in the sheet is odd. It seems to toggle on absolutely everything and, aside from that, makes it hard to use Tidy Sheet which now only lets you edit things by right clicking them.
- Chat card behavior is unwieldy, because of having to use right-click to go through options. Would it be possible to have an option for this to improve to resemble MESS more? Being able to right-click to apply damage instead of looking for the tiny fist icon would be preferable.

**Comment by Moerill** [comment]
>  Bug: Attempting to attack with an item that has a designated item track from Maestro will result in an error in console and the sound will not play.
could you please post the error? (and maybe next time follow the bug report template so i know what is going on..)

> Make it so that the GM can still attack with an item that's configured to use a resource when the resource is empty or not present. As it is currently, that's impossible. You could do that with MESS, even though a warning popped up.

temporary fix: just add that resource to your character again.  
i'll take a look at it.

> The right-click behavior to roll with adv/disadvantage in the sheet is odd. It seems to toggle on absolutely everything and, aside from that, makes it hard to use Tidy Sheet which now only lets you edit things by right clicking them.

Since every sheet does its own thing i can't (or rather don't want to, cause i don't want to learn every sheet) make it perfect for every sheet.  In my usage i'm mostly happy how it works, but am open for other suggestions. also it does not toggle on "everything" - just (almost) everything roll related.  
as for tidy.. You can edit that behaviour for compatibility sake in module settings -> tidy 5e.

> Chat card behavior is unwieldy, because of having to use right-click to go through options. Would it be possible to have an option for this to improve to resemble MESS more? Being able to right-click to apply damage instead of looking for the tiny fist icon would be preferable.

While this is the successor of MESS, its not supposed to be the same! While it got similar design ideas i do deviate from it where i was unhappy with MESS. (like the context menu, which was just a temporary thing, cause people demanded it and i had no better alternative)    
That said i'm open for suggestions on how to improve some workflow. But i do not want to add a context menu like in mess, since i find it unwieldy and slow compared to the buttons. The buttons are always placed at the same positions, making them easy to remember and fast to click (imo) .  
Is that and the whole right click workflow the most intuitive? no.. but i couldn't think of smth better mouse based and i like it.

For the future: Please one Issue per Bug / Feature request, or at least split them into bug reports / feature requests, so talking about each is easier and not one big thread.

**Comment by highnrgappalachian** [comment]
> could you please post the error? (and maybe next time follow the bug report template so i know what is going on..)

Apologies. 

- Windows 10
- Native Electron app
- FVTT 0.7.9
- MARS 1.1.0

Here's the error.
![53534](https://user-images.githubusercontent.com/70277669/104005600-fb558080-516a-11eb-9d04-651b159f976d.png)

I believe it happens only with NPCs and only when interacting through the tokens rather than the actors.

> For the future: Please one Issue per Bug / Feature request, or at least split them into bug reports / feature requests, so talking about each is easier and not one big thread.

Will do!

**Comment by Moerill** [comment]
Note to myself:
concatenate scene and token id, as in base 5e.

**Comment by Moerill** [comment]
i think i fixed it for future uses.
