### ISSUE TITLE
[BUG] Dynamic After Effects (DAE) AC Calculation Doubles when Mar-5e is enabled.

### ISSUE THREAD

**Issue by Mist-Hunter** [Moerill/fvtt-mars-5e#53]
Thank you for this awesome module! 

I've been using midi-qol previously for automation, and not to sound ungrateful for that module also, but yours is so clean and slick looking, especially the chat cards. Nothing else like it. Thanks for the time you donate to this, I and my players appreciated it.

Perhaps I should also post this bug in the DAE module? https://gitlab.com/tposney/dae/-/issues

**Describe the bug**
With DAE enabled, and set to calculate AC, Mars-5e seems to cause a miscalculation of AC, adding the AC to the base a second time. This causes crazy high AC. Disabling Mars-5e will immediately correct the issue. 

*If its related to an item, please provide a screenshot of how the item is configured. (The Items Details tab)*.
With Half-Plate + Shield (DAE)
![image](https://user-images.githubusercontent.com/6420684/104044172-c6a8ef80-5191-11eb-9fb1-8274b6f4e006.png)

With Half-Place + Shield (DAE + Mars-5e)
![image](https://user-images.githubusercontent.com/6420684/104044069-9cefc880-5191-11eb-871c-255515a6fea2.png)

FVTT 0.7.9
DnD 5e. 1.2.2
DAE 2.32
Mars-5e 1.1.0

**Comment by JLtheking2** [comment]
Agreed that this mod is amazing and that I am planning to make the switch from midi-qol to this. Both mods are amazing.

And I can vouch that this issue is happening as well on my end. Mars is causing the active effect conditional applied by DAE (example below) to work incorrectly.

@abilities.dex.mod > 3 ? 3 + 14: @abilities.dex.mod + 14

![image](https://user-images.githubusercontent.com/48344299/104051579-5054cd80-5223-11eb-8201-9f41eb952f8a.png)

**Comment by JLtheking2** [comment]
In the above example, I messed around with the ternary statement and it then functions correctly:

14+@abilities.dex.mod > 3 ? 3: @abilities.dex.mod

So I'm not too sure what's happening but somehow the changes in MARS somehow caused the original ternary statement to fail to parse.

**Comment by Moerill** [comment]
thanks for the testing.
I created an issue over at https://gitlab.com/tposney/dae/-/issues/92 , cause i got no clue what is causing this. Hoping for tposneys help here

**Comment by Moerill** [comment]
I think i fixed this one for the next patch and did not break more than i fixed with it :grimacing: 

For the interested and for me to reference:
Issue is DaE patching the ``Roll#replaceFormulaData`` method at the setup Hook.  
But i created my own roll class inheriting from Roll, and then replacing the global ``Roll`` variable with it. (So everything calling the ``Roll`` class actually calls my class.  
For some reason this resulted in the DaE patching not working (i kinda expected it to then patch my method and breaking my module...) To prevent this i did the following:
Extend Roll with my class at the ready hook, then replace the Roll variable as before.  

Now it *should* work. At least to my testing it did, i actually don't know how to use DaE, so there may still be cases that are not catched. So please test this a bit more, when Mars v1.2 is released.
