### ISSUE TITLE
[FEATURE] Option or Toggle to seperatly apply damage

### ISSUE THREAD

**Issue by tagnullde** [Moerill/fvtt-mars-5e#86]
**Is your feature request related to a problem? Please describe.**
Having setup a weapon with two or more damage types like shown in the screenshot, I just can reduce the hitpoints by it's total. Not seperatly.
![grafik](https://user-images.githubusercontent.com/44159008/108025250-72ade800-7026-11eb-9c7d-c90ae4bd6111.png)
![grafik](https://user-images.githubusercontent.com/44159008/108025484-d6381580-7026-11eb-9a2a-433ee0a9695c.png)

**Describe the solution you'd like**
An option to apply either one seperatly or both damages total. Reason might be a weapon does 1d8 damage when X but 1d12 when Y. The usual options like halving the damage or doubling should be respected too. 

**Describe alternatives you've considered**
Reducing the damage on the token by hand and not UI.
Using versatile damage option - doesn't work if the weapon already is a versatile weapon with it's own roll formula. 
Also didn't found a way to specify the damage type there.

**Additional context**
Using Tidy5e char-sheet.

**Comment by Moerill** [comment]
I ended up with the current solution, because its the only i was happy with the UI/UX. Adding individual buttons for each dmg field felt ugly and cluttered to me. If you have a UX idea in mind feel free to share and/or prototype it and i'll take a look.

For the time being: you can always just reduce the mutliplier of one the dmg field you want to apply to 0 (using right click on the result). That way it will be ignored.

**Comment by tagnullde** [comment]
I must have missed that option to reduce the damage per type. This would work for me for now.
I'll think about a UI prototype. For now I'll rest and close my case.
